In [4]:
import tensorflow as tf

In [5]:
mnist = tf.keras.datasets.mnist

In [6]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [7]:
x_train,x_test = x_train/255.0,x_test/255.0

In [8]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [24]:
predictions = model(x_train[:1]).numpy()
predictions 

array([[-0.18641582,  0.23304735,  0.17056593, -0.08189838,  0.3558769 ,
         0.39102167, -0.24225673, -0.45325354, -0.60310763, -0.21161723]],
      dtype=float32)

In [32]:
results = tf.nn.softmax(predictions)
results

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.0839802 , 0.12774605, 0.12000854, 0.09323271, 0.1444414 ,
        0.14960802, 0.07941921, 0.06431182, 0.05536177, 0.08189024]],
      dtype=float32)>

In [25]:
lose_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [33]:
lose_fn(y_train[:1],predictions).numpy()

1.8997366

In [34]:
y_train[:1]

array([5], dtype=uint8)

In [35]:
model.compile(optimizer='adam',
             loss=lose_fn,
             metrics=['accuracy'])

In [36]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2991 - accuracy: 0.9144
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1488 - accuracy: 0.9563
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1081 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0902 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0765 - accuracy: 0.9756


In [37]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 0s 814us/step - loss: 0.0806 - accuracy: 0.9759


[0.08058881759643555, 0.9758999943733215]

In [38]:
probablity_model = tf.keras.models.Sequential([model,tf.keras.layers.Softmax()])

In [52]:
import numpy as np
test = tf.expand_dims(x_train[10],axis=0)
np.argmax(model.predict(test))

3

In [53]:
y_train[10]

3